name: build and push docker image to docker hub 
on:
  push:    

jobs:
  build-image: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image 
        run: |
          # get the current date and time with seconds
          current_date=$(date +"%Y%m%d%H%M%S")
          docker build -t ${{ secrets.DOCKER_USER }}/myapp:$current_date .

      - name: show docker images
        run: |
          docker image ls